// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solution.Persistence.Contexts;

#nullable disable

namespace Solution.Persistence.Migrations
{
    [DbContext(typeof(SogfDbContext))]
    [Migration("20251104195250_ImprovedMissionRelationshipWithPilotoPerdedorReferenceAndDeleteBehavior")]
    partial class ImprovedMissionRelationshipWithPilotoPerdedorReferenceAndDeleteBehavior
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Solution.Domain.Model.Missao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("NaveDesignadaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NaveDesignadaId");

                    b.ToTable("missoes", (string)null);
                });

            modelBuilder.Entity("Solution.Domain.Model.Nave", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Naves", (string)null);
                });

            modelBuilder.Entity("Solution.Domain.Model.RelatorioCombate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoDeEventos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PilotoPerdedorId")
                        .HasColumnType("bigint");

                    b.Property<long>("PilotoVencedorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PilotoPerdedorId");

                    b.HasIndex("PilotoVencedorId");

                    b.ToTable("relatorioCombate", (string)null);
                });

            modelBuilder.Entity("Solution.Domain.Model.Tripulante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("NaveAtualId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NavePilotadaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NaveAtualId");

                    b.HasIndex("NavePilotadaId")
                        .IsUnique()
                        .HasFilter("[NavePilotadaId] IS NOT NULL");

                    b.ToTable("Tripulantes", (string)null);
                });

            modelBuilder.Entity("Solution.Domain.Model.Missao", b =>
                {
                    b.HasOne("Solution.Domain.Model.Nave", "NaveDesignada")
                        .WithMany("Missoes")
                        .HasForeignKey("NaveDesignadaId");

                    b.Navigation("NaveDesignada");
                });

            modelBuilder.Entity("Solution.Domain.Model.RelatorioCombate", b =>
                {
                    b.HasOne("Solution.Domain.Model.Tripulante", "PilotoPerdedor")
                        .WithMany("HistoricoDeDerrotas")
                        .HasForeignKey("PilotoPerdedorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Solution.Domain.Model.Tripulante", "PilotoVencedor")
                        .WithMany("HistoricoDeCombates")
                        .HasForeignKey("PilotoVencedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PilotoPerdedor");

                    b.Navigation("PilotoVencedor");
                });

            modelBuilder.Entity("Solution.Domain.Model.Tripulante", b =>
                {
                    b.HasOne("Solution.Domain.Model.Nave", "NaveAtual")
                        .WithMany("Tripulantes")
                        .HasForeignKey("NaveAtualId");

                    b.HasOne("Solution.Domain.Model.Nave", "NavePilotada")
                        .WithOne("Piloto")
                        .HasForeignKey("Solution.Domain.Model.Tripulante", "NavePilotadaId");

                    b.Navigation("NaveAtual");

                    b.Navigation("NavePilotada");
                });

            modelBuilder.Entity("Solution.Domain.Model.Nave", b =>
                {
                    b.Navigation("Missoes");

                    b.Navigation("Piloto");

                    b.Navigation("Tripulantes");
                });

            modelBuilder.Entity("Solution.Domain.Model.Tripulante", b =>
                {
                    b.Navigation("HistoricoDeCombates");

                    b.Navigation("HistoricoDeDerrotas");
                });
#pragma warning restore 612, 618
        }
    }
}
