// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solution.Persistence.Contexts;

#nullable disable

namespace Solution.Persistence.Migrations
{
    [DbContext(typeof(SogfDbContext))]
    [Migration("20251110184456_userSalt")]
    partial class userSalt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SOGF.Domain.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SOGF.Domain.Model.Faccao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelAmeaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StatusDiplomatico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faccoes", (string)null);
                });

            modelBuilder.Entity("SOGF.Domain.Model.Missao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<long>("NaveId")
                        .HasColumnType("bigint");

                    b.Property<int>("ObjetivoMissao")
                        .HasColumnType("int");

                    b.Property<long>("PilotoId")
                        .HasColumnType("bigint");

                    b.Property<int>("SetorGalatico")
                        .HasColumnType("int");

                    b.Property<int>("StatusMissao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("missoes", (string)null);
                });

            modelBuilder.Entity("SOGF.Domain.Model.Nave", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CapacidadeTripulacao")
                        .HasColumnType("bigint");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<long>("FaccaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FaccaoId");

                    b.ToTable("Naves", (string)null);
                });

            modelBuilder.Entity("SOGF.Domain.Model.Piloto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pilotos", (string)null);
                });

            modelBuilder.Entity("SOGF.Domain.Model.RelatorioCombate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoTatica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FaccaoVencedoraId")
                        .HasColumnType("bigint");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("relatorioCombate", (string)null);
                });

            modelBuilder.Entity("SOGF.Domain.Model.Tripulante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tripulantes", (string)null);
                });

            modelBuilder.Entity("SOGF.Domain.Entity.User", b =>
                {
                    b.OwnsMany("SOGF.Domain.UserRoles", "Roles", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<DateTime>("DataAtualizacao")
                                .ValueGeneratedOnUpdate()
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("DataCriacao")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Role")
                                .HasColumnType("int");

                            b1.Property<long>("userId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("userId");

                            b1.ToTable("usuariosRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("userId");
                        });

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SOGF.Domain.Model.Missao", b =>
                {
                    b.OwnsMany("SOGF.Domain.Model.MissaoTripulantes", "Tripulantes", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<long>("MissaoId")
                                .HasColumnType("bigint");

                            b1.Property<long>("TripulanteId")
                                .HasColumnType("bigint")
                                .HasColumnName("TripulanteId");

                            b1.HasKey("Id");

                            b1.HasIndex("MissaoId", "TripulanteId")
                                .IsUnique();

                            b1.ToTable("missaoTripulantes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MissaoId");
                        });

                    b.Navigation("Tripulantes");
                });

            modelBuilder.Entity("SOGF.Domain.Model.Nave", b =>
                {
                    b.HasOne("SOGF.Domain.Model.Faccao", "Faccao")
                        .WithMany("Naves")
                        .HasForeignKey("FaccaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faccao");
                });

            modelBuilder.Entity("SOGF.Domain.Model.RelatorioCombate", b =>
                {
                    b.OwnsMany("SOGF.Domain.Model.EngajamentoCombate", "NavesEngajadas", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<DateTime>("DataAtualizacao")
                                .ValueGeneratedOnUpdate()
                                .HasColumnType("datetime2");

                            b1.Property<long>("MissaoId")
                                .HasColumnType("bigint");

                            b1.Property<long>("NaveId")
                                .HasColumnType("bigint");

                            b1.Property<long>("PilotoId")
                                .HasColumnType("bigint");

                            b1.Property<long>("RelatorioCombateId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Resultado")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("RelatorioCombateId", "NaveId", "PilotoId")
                                .IsUnique();

                            b1.ToTable("EngajamentosCombate", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RelatorioCombateId");
                        });

                    b.Navigation("NavesEngajadas");
                });

            modelBuilder.Entity("SOGF.Domain.Model.Faccao", b =>
                {
                    b.Navigation("Naves");
                });
#pragma warning restore 612, 618
        }
    }
}
