// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solution.Persistence.Contexts;

#nullable disable

namespace Solution.Persistence.Migrations
{
    [DbContext(typeof(SogfDbContext))]
    partial class SogfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SOGF.Domain.Entity.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("SOGF.Domain.Model.Faccao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<string>("NivelAmeaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StatusDiplomatico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faccoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelAmeaca = "Alto",
                            Nome = "Império Galáctico",
                            StatusDiplomatico = "Agressivo"
                        },
                        new
                        {
                            Id = 2L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelAmeaca = "Alto",
                            Nome = "Aliança Rebelde",
                            StatusDiplomatico = "Pacifico"
                        },
                        new
                        {
                            Id = 3L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelAmeaca = "Baixo",
                            Nome = "Nova República",
                            StatusDiplomatico = "Pacifico"
                        },
                        new
                        {
                            Id = 4L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelAmeaca = "Alto",
                            Nome = "Primeira Ordem",
                            StatusDiplomatico = "Agressivo"
                        },
                        new
                        {
                            Id = 5L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelAmeaca = "Medio",
                            Nome = "Resistência",
                            StatusDiplomatico = "Pacifico"
                        },
                        new
                        {
                            Id = 6L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelAmeaca = "Medio",
                            Nome = "Guilda de Caçadores",
                            StatusDiplomatico = "Neutro"
                        },
                        new
                        {
                            Id = 7L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelAmeaca = "Medio",
                            Nome = "Clãs Mandalorianos",
                            StatusDiplomatico = "Neutro"
                        },
                        new
                        {
                            Id = 8L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelAmeaca = "Alto",
                            Nome = "Sindicatos Hutt",
                            StatusDiplomatico = "Neutro"
                        });
                });

            modelBuilder.Entity("SOGF.Domain.Model.Missao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<long>("NaveId")
                        .HasColumnType("bigint");

                    b.Property<int>("ObjetivoMissao")
                        .HasColumnType("int");

                    b.Property<long>("PilotoId")
                        .HasColumnType("bigint");

                    b.Property<int>("SetorGalatico")
                        .HasColumnType("int");

                    b.Property<int>("StatusMissao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("missoes", (string)null);
                });

            modelBuilder.Entity("SOGF.Domain.Model.Nave", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CapacidadeTripulacao")
                        .HasColumnType("bigint");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<long>("FaccaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FaccaoId");

                    b.ToTable("Naves", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CapacidadeTripulacao = 5400L,
                            Classe = "CruzadorDeBatalha",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 1L,
                            Nome = "Home One",
                            Status = "Pronta"
                        },
                        new
                        {
                            Id = 2L,
                            CapacidadeTripulacao = 5200L,
                            Classe = "CruzadorDeBatalha",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 2L,
                            Nome = "Liberty (MC80)",
                            Status = "Pronta"
                        },
                        new
                        {
                            Id = 3L,
                            CapacidadeTripulacao = 6L,
                            Classe = "Utilitario",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 4L,
                            Nome = "Millennium Falcon",
                            Status = "Pronta"
                        },
                        new
                        {
                            Id = 4L,
                            CapacidadeTripulacao = 6L,
                            Classe = "Utilitario",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 5L,
                            Nome = "Ghost",
                            Status = "Pronta"
                        },
                        new
                        {
                            Id = 5L,
                            CapacidadeTripulacao = 1L,
                            Classe = "Patrulha",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 2L,
                            Nome = "Red Five (X-Wing)",
                            Status = "Pronta"
                        },
                        new
                        {
                            Id = 6L,
                            CapacidadeTripulacao = 2L,
                            Classe = "Patrulha",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 1L,
                            Nome = "Gold Leader (Y-Wing)",
                            Status = "EmReparo"
                        },
                        new
                        {
                            Id = 7L,
                            CapacidadeTripulacao = 37000L,
                            Classe = "CruzadorDeBatalha",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 6L,
                            Nome = "Devastator (ISD)",
                            Status = "Pronta"
                        },
                        new
                        {
                            Id = 8L,
                            CapacidadeTripulacao = 28000L,
                            Classe = "CruzadorDeBatalha",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 2L,
                            Nome = "Interdictor",
                            Status = "Pronta"
                        },
                        new
                        {
                            Id = 9L,
                            CapacidadeTripulacao = 1L,
                            Classe = "Patrulha",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 4L,
                            Nome = "TIE Squadron",
                            Status = "Pronta"
                        },
                        new
                        {
                            Id = 10L,
                            CapacidadeTripulacao = 60000L,
                            Classe = "CruzadorDeBatalha",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 2L,
                            Nome = "Finalizer (SD FO)",
                            Status = "EmReparo"
                        },
                        new
                        {
                            Id = 11L,
                            CapacidadeTripulacao = 1L,
                            Classe = "Utilitario",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 6L,
                            Nome = "Slave I",
                            Status = "Pronta"
                        },
                        new
                        {
                            Id = 12L,
                            CapacidadeTripulacao = 1L,
                            Classe = "Patrulha",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 7L,
                            Nome = "Gauntlet Fighter",
                            Status = "Pronta"
                        },
                        new
                        {
                            Id = 13L,
                            CapacidadeTripulacao = 90L,
                            Classe = "Utilitario",
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FaccaoId = 8L,
                            Nome = "Khetanna",
                            Status = "Pronta"
                        });
                });

            modelBuilder.Entity("SOGF.Domain.Model.Piloto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pilotos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Luke Skywalker",
                            Patente = "Capitao"
                        },
                        new
                        {
                            Id = 2L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Wedge Antilles",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 3L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Poe Dameron",
                            Patente = "Capitao"
                        },
                        new
                        {
                            Id = 4L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Biggs Darklighter",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 5L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jek Porkins",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 6L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Han Solo",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 7L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Leia Organa",
                            Patente = "Capitao"
                        },
                        new
                        {
                            Id = 8L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Cassian Andor",
                            Patente = "Capitao"
                        },
                        new
                        {
                            Id = 9L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jyn Erso",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 10L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Tycho Celchu",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 11L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Wes Janson",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 12L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Garven Dreis",
                            Patente = "Capitao"
                        });
                });

            modelBuilder.Entity("SOGF.Domain.Model.RelatorioCombate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoTatica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FaccaoVencedoraId")
                        .HasColumnType("bigint");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("relatorioCombate", (string)null);
                });

            modelBuilder.Entity("SOGF.Domain.Model.Tripulante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getDate()");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tripulantes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Estrategista",
                            Nome = "Luke Skywalker",
                            Patente = "Capitao"
                        },
                        new
                        {
                            Id = 2L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Medicina",
                            Nome = "Wedge Antilles",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 3L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Engenharia",
                            Nome = "Chewbacca",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 4L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Batalha",
                            Nome = "Leia Organa",
                            Patente = "Capitao"
                        },
                        new
                        {
                            Id = 5L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Engenharia",
                            Nome = "Han Solo",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 6L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Estrategista",
                            Nome = "Poe Dameron",
                            Patente = "Capitao"
                        },
                        new
                        {
                            Id = 7L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Medicina",
                            Nome = "Finn",
                            Patente = "Cadete"
                        },
                        new
                        {
                            Id = 8L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Batalha",
                            Nome = "Rey",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 9L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Engenharia",
                            Nome = "Rose Tico",
                            Patente = "Cadete"
                        },
                        new
                        {
                            Id = 10L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Medicina",
                            Nome = "Biggs Darklighter",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 11L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Batalha",
                            Nome = "Jek Porkins",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 12L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Engenharia",
                            Nome = "Dak Ralter",
                            Patente = "Cadete"
                        },
                        new
                        {
                            Id = 13L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Batalha",
                            Nome = "Lando Calrissian",
                            Patente = "Capitao"
                        },
                        new
                        {
                            Id = 14L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Engenharia",
                            Nome = "Nien Nunb",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 15L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Engenharia",
                            Nome = "Bodhi Rook",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 16L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Medicina",
                            Nome = "Cassian Andor",
                            Patente = "Capitao"
                        },
                        new
                        {
                            Id = 17L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Medicina",
                            Nome = "Jyn Erso",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 18L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Engenharia",
                            Nome = "Sabine Wren",
                            Patente = "Tenente"
                        },
                        new
                        {
                            Id = 19L,
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Especialidade = "Batalha",
                            Nome = "Hera Syndulla",
                            Patente = "Capitao"
                        });
                });

            modelBuilder.Entity("SOGF.Domain.Entity.User", b =>
                {
                    b.OwnsMany("SOGF.Domain.UserRoles", "Roles", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<DateTime>("DataAtualizacao")
                                .ValueGeneratedOnUpdate()
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("DataCriacao")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Role")
                                .HasColumnType("int");

                            b1.Property<long>("userId")
                                .HasColumnType("bigint");

                            b1.HasKey("Id");

                            b1.HasIndex("userId");

                            b1.ToTable("usuariosRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("userId");
                        });

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SOGF.Domain.Model.Missao", b =>
                {
                    b.OwnsMany("SOGF.Domain.Model.MissaoTripulantes", "Tripulantes", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<long>("MissaoId")
                                .HasColumnType("bigint");

                            b1.Property<long>("TripulanteId")
                                .HasColumnType("bigint")
                                .HasColumnName("TripulanteId");

                            b1.HasKey("Id");

                            b1.HasIndex("MissaoId", "TripulanteId")
                                .IsUnique();

                            b1.ToTable("missaoTripulantes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MissaoId");
                        });

                    b.Navigation("Tripulantes");
                });

            modelBuilder.Entity("SOGF.Domain.Model.Nave", b =>
                {
                    b.HasOne("SOGF.Domain.Model.Faccao", "Faccao")
                        .WithMany("Naves")
                        .HasForeignKey("FaccaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faccao");
                });

            modelBuilder.Entity("SOGF.Domain.Model.RelatorioCombate", b =>
                {
                    b.OwnsMany("SOGF.Domain.Model.EngajamentoCombate", "NavesEngajadas", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<DateTime>("DataAtualizacao")
                                .ValueGeneratedOnUpdate()
                                .HasColumnType("datetime2");

                            b1.Property<long>("MissaoId")
                                .HasColumnType("bigint");

                            b1.Property<long>("NaveId")
                                .HasColumnType("bigint");

                            b1.Property<long>("PilotoId")
                                .HasColumnType("bigint");

                            b1.Property<long>("RelatorioCombateId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Resultado")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("RelatorioCombateId", "NaveId", "PilotoId")
                                .IsUnique();

                            b1.ToTable("EngajamentosCombate", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RelatorioCombateId");
                        });

                    b.Navigation("NavesEngajadas");
                });

            modelBuilder.Entity("SOGF.Domain.Model.Faccao", b =>
                {
                    b.Navigation("Naves");
                });
#pragma warning restore 612, 618
        }
    }
}
